### PR TITLE
Seperate `loop` and `autoplay` from `queue` command

### PR DESCRIPTION
**Pull request by Will3126**
This probably doesn't work because I don't know how I.R.I.S. fully works, but it's worth the shot.
I hope you can add something like this!

### CODE REVIEW

**Comment by MidSpike** [comment]
Along with the new command file, I suggest that the sub-command `queue loop` is removed.

**Comment by MidSpike** [comment]
@Will3126 under the same considerations as making `loop` it's own command; what are your opinions on making `autoplay` it's own command?

**Comment by Will3126** [comment]
Really all I want is a `%loop` instead of `%q loop` as the command is more recognized in other music bots.

**Comment by MidSpike** [comment]
After consideration, I will be making the autoplay sub-command it's own command as well.

**Comment by MidSpike** [comment]
This PR should be ready to merge with the master branch

**Review by MidSpike — APPROVED** [review]

**Pull request merged**
